name: Auto Release GeoIP

on:
  push:
    branches:
      - main
    paths:
      - 'release/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse Date, Format Name and Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd release
          
          MARKER_FILE=$(ls | grep -E '^[0-9]{6}$' | head -n 1)
          
          if [ -z "$MARKER_FILE" ]; then
            echo "Маркерный файл не найден в папке release. Пропуск."
            exit 0
          fi
          
          TAG=$MARKER_FILE
          
          YY=${TAG:0:2}
          MM=${TAG:2:2}
          DD=${TAG:4:2}
          

          MM=$((10#$MM))
          DD=$((10#$DD))
          
          RELEASE_NAME="zkeen-ip-${YY}.${MM}.${DD}"
          
          for file in zkeenip.dat ru ru6; do
            if [ ! -f "$file" ]; then
              echo "Ошибка: Файл $file не найден в папке release!"
              exit 1
            fi
          done
          
          NOTES="![downloads](https://img.shields.io/github/downloads/jameszeroX/zkeen-ip/${TAG}/total?label=downloads)"
          
          if gh release view "$TAG" > /dev/null 2>&1; then
            echo "Релиз с тегом $TAG уже существует. Обновление не требуется."
            exit 0
          fi
          
          gh release create "$TAG" \
            zkeenip.dat ru ru6 \
            --title "$RELEASE_NAME" \
            --notes "$NOTES"